# Generated by Django 5.0.1 on 2024-01-26 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_permission_delete_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('view_all', 'Can view all inf')]},
        ),
    ]
