# Generated by Django 5.0.1 on 2024-01-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('view_all_hahaha', 'Can view all infddd')]},
        ),
    ]
