# Generated by Django 5.0.1 on 2024-01-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_permission_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'permissions': [('view_all', 'Can view all information')]},
        ),
    ]
