# Generated by Django 5.0.1 on 2024-01-26 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_permission_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='NewPermission',
        ),
    ]
