# Generated by Django 5.0.1 on 2024-01-26 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_permission_newpermission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewPermission',
        ),
    ]
